### PR TITLE
Extend number of string or num argument placeholders to be unlimited

### PR DESCRIPTION
**Pull request by XinyueZ**
I am not sure whether it was your intension to ignore more possible string-based arguments or number based ones. 
Maybe I am wrong. But in our project, we really need to have arguments more than two under the hood.
So I provide this PR, maybe you can extend the library sincerely 😉 

Thank you.

### CODE REVIEW

**Comment by vishna** [comment]
Thanks for your PR, I'll take a look at it ASAP.

**Comment by vishna** [comment]
So your change is merged but had to push another commit on top, otherwise it was breaking some strings.xml files:

https://github.com/vishna/as2f/commit/679c4c0ecd8a1d54bc508c09f359d98c27c778c4

All test were green. Probably should write tests with those offending strings.xml.

Again, thanks a lot for spotting this 2 args limitation 😅 🙇 Will publish to pub.dev soon.

**Comment by XinyueZ** [comment]
@vishna when could be the next release ?

**Comment by vishna** [comment]
should be 7 days ago
https://pub.dev/packages/as2f/changelog

**Comment by XinyueZ** [comment]
@vishna thank you

**Pull request closed without merging**
